#!/bin/bash

# First build the shared library for the MessageDistributor.
g++ -I ../FlexBarrier/ -c -g -std=c++17 -fPIC MessageDistributor.cpp
g++ -I ../FlexBarrier/ -g -std=c++17 -fPIC -shared MessageDistributor.o -o libMessageDistributor.so

# Now build the Examples.

linkerFlags="-L ../FlexBarrier -lpthread -lFlexBarrier -lPocoFoundation -L. -lMessageDistributor"

for fileItem in $(ls Example*.cpp)
do
	g++ -I ../FlexBarrier/ -g -std=c++17 $fileItem -o ${fileItem%.cpp}.out $linkerFlags
done

# Remove object files at the end. 
rm -f *.o
